### ISSUE TITLE
Incompatible with Current RN Versions

### ISSUE THREAD

**Issue by kevinvangelder** [liuchungui/react-native-star-rating#3]
Trying to use this component in a project using a recent version of RN fails:

![incompatible](https://cloud.githubusercontent.com/assets/1771152/23688264/4cd8276e-0368-11e7-8f63-24071475a335.PNG)

It seems like this project has been inactive for a while, but if I were to submit a pull request to fix this would it be merged?

**Comment by liuchungui** [comment]
@kevinvangelder  That would be great. Thank you for all your support.
